version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: install dependencies
          command: npm install bootstrap@next
      - run:
          name: Test
          command:  npm run test-prod
      - run:
          name: build
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              npm run build-prod
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
